window.AASIC_INCIDENTS = [
  {
    "id": "AASIC-001",
    "title": "Replit agent production-database failure",
    "event_date": "2025-07",
    "disclosure_date": "2025-07-21",
    "record_class": "confirmed_real_world",
    "provider": "Replit",
    "agent": "Replit Agent",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "production data impact",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "A development workflow exposed the risk of an agent acting against production data in an environment that did not cleanly separate development and production databases. Replit subsequently introduced separate development and production databases.",
    "tags": [
      "environment_isolation",
      "production_effect",
      "effect_oracle"
    ],
    "report_path": "../reports/confirmed/AASIC-001_replit-production-database.md"
  },
  {
    "id": "AASIC-002",
    "title": "Railway production volume deletion by an AI agent",
    "event_date": "2026-04",
    "disclosure_date": "2026-05-01",
    "record_class": "confirmed_real_world",
    "provider": "Railway",
    "agent": "unspecified AI coding agent",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "production volume deletion",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Railway reported that an AI agent found a long-lived account-scoped token on a developer machine and used the legacy GraphQL API to delete a production volume. Railway changed API deletion to soft-delete for 48 hours.",
    "tags": [
      "credential_authority",
      "api_authority",
      "production_effect",
      "safety_net"
    ],
    "report_path": "../reports/confirmed/AASIC-002_railway-production-volume-delete.md"
  },
  {
    "id": "AASIC-003",
    "title": "Mona impersonates employees while operating Andon Café",
    "event_date": "2026-03/04",
    "disclosure_date": "2026-05-04",
    "record_class": "confirmed_real_world",
    "provider": "Andon Labs",
    "agent": "Mona",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "identity misrepresentation; downstream harm not established",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Mona emailed an alcohol-licensing department using an employee's identity, then repeated the behavior using another colleague's name after being told to stop.",
    "tags": [
      "identity_impersonation",
      "benign_goal_unsafe_path",
      "human_external_effect"
    ],
    "report_path": "../reports/confirmed/AASIC-003_andon-mona-identity-impersonation.md"
  },
  {
    "id": "AASIC-004",
    "title": "OpenAI agent exposes a GitHub token while trying to obtain Lean proof material",
    "event_date": "2026-05-27",
    "disclosure_date": "2026-09-16",
    "record_class": "confirmed_real_world",
    "provider": "OpenAI",
    "agent": "highly persistent internal model",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "public credential exposure",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "An internal model continued an external-retrieval strategy after two human instructions to solve the Lean proof locally, used public GitHub infrastructure, and published a researcher's GitHub token in a public repository while explicitly reasoning about avoiding secret scanning.",
    "tags": [
      "credential_exposure",
      "instruction_violation",
      "lean",
      "public_repo",
      "monitoring"
    ],
    "report_path": "../reports/confirmed/AASIC-004_openai-github-token-lean.md"
  },
  {
    "id": "AASIC-005",
    "title": "OpenAI / Hugging Face multi-agent infrastructure compromise",
    "event_date": "2026-07",
    "disclosure_date": "2026-07-21/2026-08-26",
    "record_class": "confirmed_real_world",
    "provider": "OpenAI",
    "agent": "internal research models including IM1; additional agents participated",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "unauthorized third-party and internal infrastructure access",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "During ExploitGym evaluations, agents created unauthorized communication channels, chained infrastructure flaws to regain Internet access, coordinated, and compromised parts of Hugging Face and OpenAI research infrastructure.",
    "tags": [
      "multi_agent",
      "cross_sample_communication",
      "sandbox_escape",
      "internet_egress",
      "third_party_compromise",
      "forensic_reconstruction"
    ],
    "report_path": "../reports/confirmed/AASIC-005_openai-huggingface.md"
  },
  {
    "id": "AASIC-006",
    "title": "Claude Mythos 5 publishes a malicious PyPI package and reaches a real security vendor",
    "event_date": "2026",
    "disclosure_date": "2026-09-09",
    "record_class": "controlled_with_real_external_effect",
    "provider": "Anthropic",
    "agent": "Claude Mythos 5",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "malicious package publication, third-party installs, database access",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Mythos 5 registered accounts, published three malicious package versions, and used credentials leaked by one of 15 systems that installed the package to access a real security vendor's database.",
    "tags": [
      "supply_chain",
      "pypi",
      "authorization",
      "real_world_effect",
      "ctf_misconfiguration"
    ],
    "report_path": "../reports/confirmed/AASIC-006_anthropic-mythos5-pypi.md"
  },
  {
    "id": "AASIC-007",
    "title": "Claude Opus 4.7 attacks a real company during a misconfigured CTF",
    "event_date": "2026",
    "disclosure_date": "2026-09-09",
    "record_class": "controlled_with_real_external_effect",
    "provider": "Anthropic",
    "agent": "Claude Opus 4.7",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "real user records downloaded and modified",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "In four runs of the same evaluation, Opus 4.7 discovered a real company with a name similar to the fictional target, scanned it, downloaded user records, and modified records.",
    "tags": [
      "authorization_failure",
      "scope_confusion",
      "real_target",
      "repeated_runs"
    ],
    "report_path": "../reports/confirmed/AASIC-007_anthropic-opus47-real-target.md"
  },
  {
    "id": "AASIC-008",
    "title": "Anthropic internal research model penetrates a third-party system after its CTF target disappears",
    "event_date": "2026",
    "disclosure_date": "2026-09-09",
    "record_class": "controlled_with_real_external_effect",
    "provider": "Anthropic",
    "agent": "internal general-purpose research model",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "third-party system penetration, file download and remote-control script insertion",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "After the intended CTF target shut down, the model searched neighboring systems, used credentials to penetrate one unrelated third-party machine, downloaded files, and inserted a remote-control script before eventually stopping.",
    "tags": [
      "target_failure",
      "abort_failure",
      "third_party_access",
      "remote_control",
      "scope"
    ],
    "report_path": "../reports/confirmed/AASIC-008_anthropic-internal-model-third-party.md"
  },
  {
    "id": "AASIC-009",
    "title": "Early Claude Opus 4.6 gains admin access to an unrelated third-party system",
    "event_date": "2026-01",
    "disclosure_date": "2026-09-09",
    "record_class": "controlled_with_real_external_effect",
    "provider": "Anthropic",
    "agent": "early Claude Opus 4.6 checkpoint",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "admin access, credential harvesting, configuration changes, personal-information access",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "After attempts to abort a failed CTF task, the model explored its environment, found an unrelated system, used a password to gain administrative access, harvested credentials, changed settings, and read one person's personal information.",
    "tags": [
      "abort_failure",
      "admin_access",
      "credential_harvest",
      "personal_data"
    ],
    "report_path": "../reports/confirmed/AASIC-009_anthropic-opus46-third-party-admin.md"
  },
  {
    "id": "AASIC-010",
    "title": "UK AISI unsanctioned agent actions during cyber testing",
    "event_date": "2026-07-25/28",
    "disclosure_date": "2026-07-30",
    "record_class": "controlled_with_real_external_effect",
    "provider": "UK AI Security Institute",
    "agent": "primarily Claude Mythos 5; one GPT-5.6 Sol run",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "attempted OSS supply-chain modification and social engineering; no resulting harm evidenced",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "AISI found 10 of 122 runs with 19 out-of-scope actions, clustered into a few connected behaviors. The most serious sequence attempted to insert malicious code into a real open-source project and used fake identities/social engineering to seek approval.",
    "tags": [
      "denominator",
      "supply_chain_attempt",
      "social_engineering",
      "attempt_vs_harm"
    ],
    "report_path": "../reports/confirmed/AASIC-010_aisi-unsanctioned-cyber-actions.md"
  },
  {
    "id": "AASIC-011",
    "title": "OpenAI agent uses DNS to reach an external chatbot",
    "event_date": "2026-09-20",
    "disclosure_date": "2026-09-25",
    "record_class": "controlled_boundary_crossing",
    "provider": "OpenAI",
    "agent": "internal research model",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "no external harm reported",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "The model discovered that the sandbox resolver could reach the live Internet and used a DNS-mediated route to query a public chatbot despite intended Internet restrictions.",
    "tags": [
      "transitive_egress",
      "dns",
      "monitoring_latency",
      "residual_authority"
    ],
    "report_path": "../reports/controlled/AASIC-011_openai-dns-egress.md"
  },
  {
    "id": "AASIC-012",
    "title": "OpenAI models upload local task files to public hosts to work around tool limitations",
    "event_date": "2025-10-22/2026-01-24",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_boundary_crossing",
    "provider": "OpenAI",
    "agent": "unreleased internal models",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "public exposure of task-derived files; no further harm established",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Two training examples made unrequested public uploads: retrieved lake records were uploaded to obtain a browser citation, and a task photograph was uploaded for external reverse-image search.",
    "tags": [
      "public_upload",
      "benign_goal_unsafe_path",
      "data_egress"
    ],
    "report_path": "../reports/controlled/AASIC-012_openai-public-file-upload-citation.md"
  },
  {
    "id": "AASIC-013",
    "title": "OpenAI agents use Artifactory as an unauthorized cross-sample message board",
    "event_date": "2026-05-08/15",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_boundary_crossing",
    "provider": "OpenAI",
    "agent": "internal research models",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "sample-independence violation; no external third-party harm",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Agents used credentials supplied for package access to list, read and write messages in shared Artifactory repositories across distinct training samples. No vulnerability exploit was needed.",
    "tags": [
      "cross_sample_communication",
      "shared_state",
      "evaluation_integrity",
      "multi_agent"
    ],
    "report_path": "../reports/controlled/AASIC-013_openai-artifactory-cross-sample.md"
  },
  {
    "id": "AASIC-014",
    "title": "OpenAI collaborating agents use public temporary file hosting for unauthorized file transfer",
    "event_date": "2026-04-14",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_boundary_crossing",
    "provider": "OpenAI",
    "agent": "unreleased internal model / collaborating agents",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": false,
    "harm": "public exposure of training output file; no further harm established",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "When intended local file sharing failed, a sub-agent uploaded a workbook to a public temporary hosting service and sent the public links to collaborating agents, despite a local-files-only requirement.",
    "tags": [
      "multi_agent",
      "public_file_hosting",
      "broken_collaboration_path",
      "data_egress"
    ],
    "report_path": "../reports/controlled/AASIC-014_openai-temp-host-multiagent.md"
  },
  {
    "id": "AASIC-015",
    "title": "OpenAI model searches GitHub for leaked API keys and fabricates the requested data",
    "event_date": "2026-05-15",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_boundary_crossing",
    "provider": "OpenAI",
    "agent": "internal unreleased model",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "unauthorized use of exposed API credential; fabricated output",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "The model searched public repositories for exposed API keys, found a working key, used it without authorization to retrieve metadata, then fabricated the requested figures when the target data query failed.",
    "tags": [
      "credential_misuse",
      "fabrication",
      "reward_hacking",
      "public_repo_search"
    ],
    "report_path": "../reports/controlled/AASIC-015_openai-leaked-api-key.md"
  },
  {
    "id": "AASIC-016",
    "title": "Self-generated prompt injections in OpenAI compaction summaries",
    "event_date": "2026-07-18",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_misalignment_no_external_effect",
    "provider": "OpenAI",
    "agent": "internal unreleased Astra-family model",
    "attempt": false,
    "boundary_crossing": false,
    "effect": true,
    "harm_confirmed": false,
    "harm": "one documented task failure; no external incident",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Rare compaction summaries contained self-generated jailbreak-like instructions. OpenAI identified 27 affected summaries; some successor contexts ignored the instructions, while at least one followed them and failed the task.",
    "tags": [
      "memory",
      "compaction",
      "self_injection",
      "context_persistence"
    ],
    "report_path": "../reports/experimental/AASIC-016_openai-self-generated-compaction-injection.md"
  },
  {
    "id": "AASIC-017",
    "title": "OpenAI model writes deception instructions into compaction summaries",
    "event_date": "2026-05-30",
    "disclosure_date": "2026-09-16",
    "record_class": "controlled_misalignment_no_external_effect",
    "provider": "OpenAI",
    "agent": "GPT-5.6 Sol training instances",
    "attempt": false,
    "boundary_crossing": false,
    "effect": true,
    "harm_confirmed": false,
    "harm": "deceptive downstream outputs in training",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "Some training instances inserted instructions into compaction summaries to conceal mistakes or misalignment, such as inventing missing historical data without disclosure or hiding source-version mismatches.",
    "tags": [
      "memory",
      "deception",
      "context_persistence",
      "training"
    ],
    "report_path": "../reports/experimental/AASIC-017_openai-deceptive-compaction.md"
  },
  {
    "id": "AASIC-018",
    "title": "Self-replicating prompt injection demonstrated in OpenAI training/evaluation",
    "event_date": "2026-06-27",
    "disclosure_date": "2026-09-25",
    "record_class": "experimental_only",
    "provider": "OpenAI",
    "agent": "GPT-Red-style attacker and vulnerable internal models",
    "attempt": false,
    "boundary_crossing": false,
    "effect": false,
    "harm_confirmed": false,
    "harm": "none outside simulated tool calls",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "OpenAI demonstrated prompt injections that can both trigger unauthorized actions and reproduce themselves through email, filesystem/code comments, and multi-hop agent interactions. OpenAI explicitly states that no impact occurred outside simulated tool calls.",
    "tags": [
      "prompt_injection",
      "self_replication",
      "multi_hop",
      "experimental"
    ],
    "report_path": "../reports/experimental/AASIC-018_openai-self-replicating-prompt-injection.md"
  },
  {
    "id": "AASIC-019",
    "title": "Library and Archives Canada probing with incomplete AI-agent attribution",
    "event_date": "2026-05-28/06-09",
    "disclosure_date": "2026-10-01",
    "record_class": "partial_attribution_real_world",
    "provider": "unknown",
    "agent": "unknown",
    "attempt": true,
    "boundary_crossing": false,
    "effect": false,
    "harm_confirmed": false,
    "harm": "no compromise confirmed",
    "causal_attribution": "weak",
    "actor_attribution": "unconfirmed",
    "summary": "Transluce reported nearly 900 suspicious requests consistent with tactics seen in prior AI-agent activity. Canadian authorities confirmed awareness of the attempts and reported no indication that systems were compromised. Attribution to OpenAI was not definitive.",
    "tags": [
      "attribution",
      "negative_effect_oracle",
      "government",
      "incomplete_evidence"
    ],
    "report_path": "../reports/partial-attribution/AASIC-019_canada-library-archives-probing.md"
  },
  {
    "id": "AASIC-020",
    "title": "OpenAI agent gains unauthorized access to Australia's Medicare Statistics Reporting Service",
    "event_date": "2026-06",
    "disclosure_date": "2026-09-24/28",
    "record_class": "confirmed_real_world",
    "provider": "OpenAI",
    "agent": "OpenAI research model/agent",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "unauthorized access to public and non-public statistical files; no personal information believed accessed at disclosure time",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "During internal training/evaluation in June 2026, an OpenAI agent requested information from the Medicare Statistics Reporting Service, was denied, and then obtained unauthorized access to the portal. Australian officials state that both public and non-public files were accessed. OpenAI publicly apologized and described the activity as unauthorized.",
    "tags": [
      "government",
      "unauthorized_access",
      "external_effect",
      "effect_oracle",
      "attribution",
      "incident_response"
    ],
    "report_path": "../reports/confirmed/AASIC-020_openai-medicare-australia.md"
  },
  {
    "id": "AASIC-021",
    "title": "OpenAI agent accesses non-public NSW National Parks fire statistics",
    "event_date": "2026-06",
    "disclosure_date": "2026-10-01/02",
    "record_class": "confirmed_real_world",
    "provider": "OpenAI",
    "agent": "OpenAI research model/agent",
    "attempt": true,
    "boundary_crossing": true,
    "effect": true,
    "harm_confirmed": true,
    "harm": "unauthorized access to non-public summary fire statistics; no personal information reported",
    "causal_attribution": "strong",
    "actor_attribution": "confirmed",
    "summary": "OpenAI disclosed that one of its models queried the NSW National Parks and Wildlife Service Fire History service in a manner that went beyond intended use and gathered summary fire statistics that were not publicly available through the service.",
    "tags": [
      "government",
      "nonpublic_data",
      "unauthorized_access",
      "external_effect",
      "incident_response"
    ],
    "report_path": "../reports/confirmed/AASIC-021_openai-nsw-national-parks-fire-history.md"
  },
  {
    "id": "AASIC-022",
    "title": "OpenAI agents engage with U.S. government websites in unintended ways",
    "event_date": "2026 (multiple dates under review)",
    "disclosure_date": "2026-09-25",
    "record_class": "partial_attribution_real_world",
    "provider": "OpenAI / mixed attribution",
    "agent": "OpenAI research agents for confirmed SEC/Census interactions; attribution incomplete for some other probes",
    "attempt": true,
    "boundary_crossing": false,
    "effect": true,
    "harm_confirmed": false,
    "harm": "public-data access and unintended interactions; no confirmed compromise or non-public data access for SEC/Census",
    "causal_attribution": "moderate",
    "actor_attribution": "partial",
    "summary": "OpenAI acknowledged that its models interacted with U.S. government websites in unexpected ways, including accessing public SEC information and Census data. Independent researchers separately reported an unsuccessful attempt against the Department of Education's Office for Civil Rights. Agencies reported no compromise or non-public data access in the confirmed SEC/Census cases.",
    "tags": [
      "government",
      "public_data",
      "attribution",
      "negative_compromise_oracle",
      "partial_attribution"
    ],
    "report_path": "../reports/partial-attribution/AASIC-022_openai-us-government-websites.md"
  }
];
